### ISSUE TITLE
Change the minimum iOS Version  to iOS 10 or 11

### ISSUE THREAD

**Issue by theInternauts** [zinc-collective/mp-shake-it-photo#20]
I am unclear what will happen to legacy support if I deploy a new binary with iOS 14.0 as the build target.  Which phones will be able to run the new binary?  How to I maintain support for phones that are a few models behind?

**Comment by zspencer** [comment]
There's an interesting article on how to decide what to set the minimum iOS version to here: https://www.avanderlee.com/workflow/minimum-ios-version/

My gut says we should do a quick skim of the iOS versions we are getting reported back to us, and only drop the versions with < X% users. What do you think?

**Comment by zspencer** [comment]
@theInternauts - Can you confirm that you've updated the binary to use iOS 10 or 11+? I am not Smert enough at iOS to figure it out from the Git History. If so, we can close this out!

**Comment by theInternauts** [comment]
This milestone was has been eclipsed by the release of v3.3.0 that supports iOS 14.1+
