### ISSUE TITLE
Make it easier to "Swipe up" from the app on smaller screens

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#26]
The location of our buttons on smaller screens appear to make them really easy to "tap" when someone is swiping up. We may want to add some [margin? padding?](https://uxengineer.com/padding-vs-margin/) to make it a bit less likely that we're getting in the way of Operationg-System level gestures.

>Subject: Usability suggestion
> Message: Hi. Another suggestion: on the screen with the four buttons at the bottom (export, import, camera, and settings), please move these up and give more room. Currently it’s sometimes tricky to trap on these because it’s so close to the “swipe up” area (to leave the app) on my iPhone XS. 
> Also, sometimes it freezes on this screen. 
> Thanks for maintaining this great app!

Permalink: https://groups.google.com/a/zinc.coop/d/msgid/momentpark/1461293483.18650.1618315271905.JavaMail.root%40v6-aux-6bb967d854-6vp85

**Comment by zspencer** [comment]
@theInternauts - I've added this to the 3.3.0 milestone as well; but I could see us doing a 3.2.7 release if there are other bug-fixes we want to make for ShakeItPhoto; especially if we don't have the capacity to add new features.

Thoughts?

**Comment by ErnieBarreto** [comment]
Hi, I'm Ernie, the guy who sent in the comment above. I mentioned a "freeze". This is how I can reproduce it. Open the app, hit 'cancel', tap the + for import, select a different folder of photos, scroll aggressively to the top -- so aggressively that you swipe away the photo library and return to the app, but all you see is the logo. Tap on the screen. At this point the upload, import, and camera buttons are grayed out and don't work, but you can pick the gear for settings. If I repeatedly tap on the camera button (which is too far on the edge), eventually I return to the camera.

**Comment by zspencer** [comment]
Thank you @ErnieBarreto! That will really help as we try to reproduce and resolve the issue!

**Comment by zspencer** [comment]
I believe this was fixed in the 3.5.0 release, so I am making it as closed unless @theInternauts says it's not.
