### ISSUE TITLE
Update phrasing to be compatible with Polaroids preference regarding "Polaroid frame photos" instead of "Polaroid photos"

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/mp-shake-it-photo#32]
> Hi Zee, I’m jumping in here to help get your 2022 renewal squared away. I believe we would just need to make one minor change and we should be good. Please see below from our legal team. If you can let me know which of the two options you would prefer I should be able to get this processed before the end of the week.
>
> We are willing to offer another renewal for one more year. However, we do have an issue with the use of the POLAROID wordmark in the SHAKEIT app. They use the sentence “Take Polaroid photos with your iPhone”. This sentence suggests that it concerns a genuine Polaroid picture, while it is a photo including the Polaroid picture format. We would like to avoid any reference to the term Polaroid photo/picture, while it is not a genuine Polaroid picture. Therefore, we request to change the said sentence to: “Take Polaroid format photos with your iPhone” or to “Take Polaroid frame photos with your iPhone”. Please let me know if this works. If so, we will draft the amendment to the contract for another year.
https://groups.google.com/a/zinc.coop/g/momentpark/c/zCkbgYTMuJs

**Comment by zspencer** [comment]
@user512 / @theInternauts - Looks like the phrasing isn't _quite_ what they wanted. Any chance we can update to use `Polaroid BV` instead of `PLR IP Holdings LLC`

Apologies for the churn :(

>Hi Zee, no problem. I just updated the app and it looks like the copy still references PLR IP Holdings instead of Polaroid BV.
> ![Image](https://user-images.githubusercontent.com/50284/157993844-69962393-cea9-4795-bcd0-c82817b05a68.png)

**Comment by user512** [comment]
Yes, will get it fixed this week.

**Comment by zspencer** [comment]
Thank's @user512 ! Appreciate it!

**Comment by zspencer** [comment]
This was resolved back in 2022.
