### ISSUE TITLE
iPhone 12 pro not able to tap bottom bar button

### ISSUE THREAD

**Issue by user512** [zinc-collective/mp-shake-it-photo#35]
>  Dear all,
> 
> I just installed version 3.3.1 from the AppStore on my iPhone 12 Pro. To go to the settings menu I tap on "Cancel" the then on the little gear on the next page. In this new version I'm not able to tap on one of the "buttons" ( Share / + / Camera / Settings ) on the bottom of the screen at all. If I tap it the app goes back to the first screen.
>
> Could you please correct it.

See: https://groups.google.com/a/zinc.coop/d/msgid/momentpark/802496184.59339.1646053510975.JavaMail.root%40v6-aux-5db744ffd7-2w42v

**Comment by zspencer** [comment]
>
> 
> Subject: No « + » button with iPhone 14 Pro
> 
> Message: Hello,
> How to use shake it with existing photos ?

- https://groups.google.com/a/zinc.coop/g/momentpark/c/HV_2b6i8mcE/m/mD7NG6wsMgAJ

**Comment by zspencer** [comment]
@theInternauts - Has this been resolved? If so I can follow up with the clients who reported it.

- Zee

**Comment by zspencer** [comment]
I've responded to the customers and am closing this out because I'm *pretty sure* it's fixed. Will re-open if we get more.
